services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mlops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  titanic-api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DB_HOST: postgres
      MODEL_NAME: titanic-classifier
      MODEL_VERSION: "1"
    depends_on:
      - postgres
    volumes:
      - ./artifacts:/app/artifacts  # Mount local artifacts with metadata
      - ./mlruns:/app/mlruns  # so MLflow can read models
    deploy:
      replicas: 3  # âœ… Run 3 instances for load balancing

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - titanic-api

volumes:
  postgres-data: