apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-predictor
  namespace: mlops-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-predictor
  template:
    metadata:
      labels:
        app: iris-predictor
      # âœ… ADD PROMETHEUS ANNOTATIONS HERE
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: iris-predictor
        image: iris-predictor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-postgresql.mlops-dev.svc.cluster.local"
        - name: MODEL_NAME
          value: "iris-classifier"
        - name: MODEL_VERSION
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"